package provider

import (
	"context"
	"encoding/pem"
	"fmt"
	"net/http"
	"time"

	"github.com/hashicorp/go-azure-helpers/lang/pointer"
	"github.com/hashicorp/go-azure-sdk/sdk/client"
	"github.com/hashicorp/go-azure-sdk/sdk/client/msgraph"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/pkg/errors"
	"github.com/scepman/terraform-provider-scepman/internal/client/scepman"
	"github.com/scepman/terraform-provider-scepman/internal/client/unauthenticated"
	"github.com/scepman/terraform-provider-scepman/internal/clients"
	"github.com/scepman/terraform-provider-scepman/internal/common"
	typesinternal "github.com/scepman/terraform-provider-scepman/internal/types"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &gsaTlsInspectionCertificateResource{}
var _ resource.ResourceWithConfigure = &gsaTlsInspectionCertificateResource{}
var _ resource.ResourceWithModifyPlan = &gsaTlsInspectionCertificateResource{}

func NewGsaTlsInspectionCertificateResource() resource.Resource {
	return &gsaTlsInspectionCertificateResource{}
}

type gsaTlsInspectionCertificateResource struct {
	client *clients.Client
}

type GsaTlsInspectionCertificateModel struct {
	Name             types.String `tfsdk:"name"`
	CommonName       types.String `tfsdk:"common_name"`
	OrganizationName types.String `tfsdk:"organization_name"`
	RenewBefore      types.Int64  `tfsdk:"renew_before"`

	Id          types.String `tfsdk:"id"`
	Status      types.String `tfsdk:"status"`
	LastUpdated types.String `tfsdk:"last_updated"`
	ExpiresAt   types.String `tfsdk:"expires_at"`
	Pem         types.String `tfsdk:"pem"`
}

func (r *gsaTlsInspectionCertificateResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	// Prevent panic if the provider has not been configured.
	if req.ProviderData == nil {
		return
	}

	c, ok := req.ProviderData.(*clients.Client)

	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *clients.Client, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)

		return
	}

	r.client = c
}

func (r *gsaTlsInspectionCertificateResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_gsa_tls_inspection_certificate"
}

func (r *gsaTlsInspectionCertificateResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: `Resource to manage a Entra GSA TLS Inspection certificate together with SCEPman.
It creates a externalCertificateAuthorityCertificate resource in Microsoft Graph, then signs it with SCEPman and updates the certificate resource with the generated certificate.
For day two operations, it will replace the certificate if it is going to expire in less than the configured renew_before threshold.

## Authorization Requirements
To be able to use this resource, the calling service principal must have the following application permissions:
- CSR.Request on the SCEPman API application in the target tenant.
- NetworkAccess.ReadWrite.All on the Microsoft Graph API application in the target tenant.
`,
		Attributes: map[string]schema.Attribute{
			"common_name": schema.StringAttribute{
				MarkdownDescription: "Common name of the certificate. Changing requires replacement.",
				Required:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"organization_name": schema.StringAttribute{
				MarkdownDescription: "Organization name of the certificate. Changing requires replacement.",
				Required:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"renew_before": schema.Int64Attribute{
				MarkdownDescription: "Number of days before the certificate expires that the provider should renew it.",
				Required:            true,
			},

			"id": schema.StringAttribute{
				MarkdownDescription: "The ID of the TLS Inspection certificate graph resource.",
				Computed:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"name": schema.StringAttribute{
				MarkdownDescription: "Name of the certificate. Autogenerated, because it needs to be unique on every certificate and would otherwise prevent rotation.",
				Computed:            true,
			},
			"status": schema.StringAttribute{
				MarkdownDescription: "Status of the certificate as reported by Microsoft Graph.",
				Computed:            true,
			},
			"last_updated": schema.StringAttribute{
				MarkdownDescription: "Timestamp of the last update of the certificate.",
				Computed:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"expires_at": schema.StringAttribute{
				MarkdownDescription: "Timestamp of the expiration of the certificate.",
				Computed:            true,
			},
			"pem": schema.StringAttribute{
				MarkdownDescription: "Certificate in PEM format.",
				Computed:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
		},
	}
}

func (r *gsaTlsInspectionCertificateResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state GsaTlsInspectionCertificateModel

	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)

	getCertResponse, notFound, err := readGraphExternalCertificateAuthorityCertificate(ctx, &resp.Diagnostics, r.client.GraphClient, state.Id.ValueString())
	if notFound {
		resp.State.RemoveResource(ctx)
		return
	}
	if err != nil {
		return
	}

	state.Id = types.StringPointerValue(getCertResponse.Id)
	state.Name = types.StringPointerValue(getCertResponse.Name)
	state.CommonName = types.StringPointerValue(getCertResponse.CommonName)
	state.OrganizationName = types.StringPointerValue(getCertResponse.OrganizationName)
	state.Status = types.StringPointerValue(getCertResponse.Status)

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *gsaTlsInspectionCertificateResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan GsaTlsInspectionCertificateModel

	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)

	if resp.Diagnostics.HasError() {
		return
	}

	plan.Name = types.StringValue(time.Now().Format("200601021504"))

	createCertRequestPayload := GraphExternalCertificateAuthorityCertificate{
		Name:             plan.Name.ValueStringPointer(),
		CommonName:       plan.CommonName.ValueStringPointer(),
		OrganizationName: plan.OrganizationName.ValueStringPointer(),
	}
	createCertResponse, certInfo, err := createGraphExternalCertificateAuthorityCertificate(
		ctx,
		&resp.Diagnostics,
		r.client.GraphClient,
		r.client.ScepmanClient,
		r.client.UnauthenticatedClient,
		createCertRequestPayload)
	if err != nil {
		resp.Diagnostics.AddError("unable to create certificate", err.Error())
		return
	}

	plan.Id = types.StringPointerValue(createCertResponse.Id)
	plan.Status = types.StringPointerValue(createCertResponse.Status)
	plan.LastUpdated = types.StringValue(time.Now().Format(time.RFC3339))
	plan.ExpiresAt = types.StringValue(certInfo.Certificate.NotAfter.Format(time.RFC3339))
	plan.Pem = types.StringValue(string(pem.EncodeToMemory(certInfo.CertificatePem)))

	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *gsaTlsInspectionCertificateResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var old, plan GsaTlsInspectionCertificateModel

	resp.Diagnostics.Append(req.State.Get(ctx, &old)...)
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)

	if resp.Diagnostics.HasError() {
		return
	}

	getCertResponse, notFound, err := readGraphExternalCertificateAuthorityCertificate(ctx, &resp.Diagnostics, r.client.GraphClient, plan.Id.ValueString())
	if notFound {
		resp.State.RemoveResource(ctx)
		return
	}
	if err != nil {
		return
	}

	plan.Status = types.StringPointerValue(getCertResponse.Status)

	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *gsaTlsInspectionCertificateResource) ModifyPlan(ctx context.Context, req resource.ModifyPlanRequest, resp *resource.ModifyPlanResponse) {
	var state, plan GsaTlsInspectionCertificateModel

	// no state = create, no checks
	if req.State.Raw.IsNull() {
		return
	}

	// no plan = delete, no checks
	if req.Plan.Raw.IsNull() {
		return
	}

	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)

	if resp.Diagnostics.HasError() {
		return
	}

	renewBefore := plan.RenewBefore.ValueInt64()
	expiresAt, err := time.Parse(time.RFC3339, state.ExpiresAt.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("unable to parse certificate expiration date", err.Error())
		return
	}

	if expiresAt.Add(-time.Duration(renewBefore) * 24 * time.Hour).Before(time.Now()) {
		resp.RequiresReplace.Append(path.Root("expires_at"))
		plan.ExpiresAt = types.StringUnknown()
	} else {
		plan.Name = state.Name
		plan.ExpiresAt = state.ExpiresAt
	}

	resp.Diagnostics.Append(resp.Plan.Set(ctx, &plan)...)
}

func (r *gsaTlsInspectionCertificateResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var plan GsaTlsInspectionCertificateModel

	resp.Diagnostics.Append(req.State.Get(ctx, &plan)...)

	if resp.Diagnostics.HasError() {
		return
	}

	err := deleteGraphExternalCertificateAuthorityCertificate(ctx, &resp.Diagnostics, r.client.GraphClient, plan.Id.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("unable to delete certificate", err.Error())
		return
	}

	resp.State.RemoveResource(ctx)
}

type GraphExternalCertificateAuthorityCertificate struct {
	Certificate               *string                          `json:"certificate,omitempty"`
	CertificateSigningRequest *string                          `json:"certificateSigningRequest,omitempty"`
	Chain                     *string                          `json:"chain,omitempty"`
	CommonName                *string                          `json:"commonName,omitempty"`
	Id                        *string                          `json:"id,omitempty"`
	Name                      *string                          `json:"name,omitempty"`
	OrganizationName          *string                          `json:"organizationName,omitempty"`
	Status                    *string                          `json:"status,omitempty"`
	Validity                  *GraphNetworkAccessValidityDates `json:"validity,omitempty"`
}

type GraphNetworkAccessValidityDates struct {
	StartDateTime  time.Time `json:"startDateTime"`
	ExpiryDateTime time.Time `json:"endDateTime"`
}

func createGraphExternalCertificateAuthorityCertificate(
	incomingContext context.Context,
	diag *diag.Diagnostics,
	c *msgraph.Client,
	sc *scepman.Client,
	uc *unauthenticated.Client,
	payload GraphExternalCertificateAuthorityCertificate) (*GraphExternalCertificateAuthorityCertificate, *typesinternal.CertificateInfo, error) {
	ctx, ctxCancel := context.WithTimeout(incomingContext, 2*time.Minute)
	defer ctxCancel()

	createCertRequest, err := c.NewRequest(ctx, client.RequestOptions{
		ContentType:         "application/json",
		ExpectedStatusCodes: []int{http.StatusCreated},
		HttpMethod:          http.MethodPost,
		Path:                "networkAccess/tls/externalCertificateAuthorityCertificates",
	})
	if err != nil {
		diag.AddError("unable to build create certificate request", err.Error())
		return nil, nil, err
	}
	err = createCertRequest.Marshal(payload)
	if err != nil {
		diag.AddError("unable to marshal create certificate request payload", err.Error())
		return nil, nil, err
	}

	response, err := c.Execute(ctx, createCertRequest)
	if err != nil {
		diag.AddError("unable to execute create certificate request", err.Error())
		return nil, nil, err
	}

	var createCertResponse GraphExternalCertificateAuthorityCertificate
	err = response.Unmarshal(&createCertResponse)
	if err != nil {
		diag.AddError("unable to unmarshal create certificate response", err.Error())
		return nil, nil, err
	}

	signWithScepmanRequestPayload, err := validateAndMarshalCsr(diag, types.StringPointerValue(createCertResponse.CertificateSigningRequest))
	if err != nil {
		diag.AddError("unable to marshal sign with scepman request payload", err.Error())
		return nil, nil, err
	}

	rootCaInfo, err := uc.GetRootCaCertificate(ctx)
	if err != nil {
		diag.AddError("unable to get root certificate", err.Error())
		return nil, nil, err
	}

	certInfo, err := sc.IssueCertificateFromCsr(ctx, signWithScepmanRequestPayload)
	if err != nil {
		diag.AddError("unable to sign certificate with scepman", err.Error())
		return nil, nil, err
	}

	certPem := string(pem.EncodeToMemory(certInfo.CertificatePem))
	caPem := string(pem.EncodeToMemory(rootCaInfo.CertificatePem))
	payload = GraphExternalCertificateAuthorityCertificate{
		Certificate: &certPem,
		Chain:       &caPem,
	}

	err = patchGraphExternalCertificateAuthorityCertificate(incomingContext, diag, c, *createCertResponse.Id, payload)
	if err != nil {
		diag.AddError("unable to patch certificate resource with generated certificate", err.Error())
		return nil, nil, err
	}

	time.Sleep(5 * time.Second)

	payload = GraphExternalCertificateAuthorityCertificate{
		Status: pointer.To("enabled"),
	}
	err = patchGraphExternalCertificateAuthorityCertificate(incomingContext, diag, c, *createCertResponse.Id, payload)
	if err != nil {
		diag.AddError("unable to patch certificate resource with enabled status", err.Error())
		return nil, nil, err
	}

	return &createCertResponse, certInfo, nil
}

func patchGraphExternalCertificateAuthorityCertificate(incomingContext context.Context, diag *diag.Diagnostics, c *msgraph.Client, certificateId string, payload GraphExternalCertificateAuthorityCertificate) error {
	ctx, ctxCancel := context.WithTimeout(incomingContext, 2*time.Minute)
	defer ctxCancel()
	patchCertRequest, err := c.NewRequest(ctx, client.RequestOptions{
		ContentType:         "application/json",
		ExpectedStatusCodes: []int{http.StatusNoContent},
		HttpMethod:          http.MethodPatch,
		Path:                fmt.Sprintf("networkAccess/tls/externalCertificateAuthorityCertificates/%s", certificateId),
	})
	if err != nil {
		diag.AddError("unable to build create certificate request", err.Error())
		return err
	}
	err = patchCertRequest.Marshal(payload)
	if err != nil {
		diag.AddError("unable to marshal create certificate request payload", err.Error())
		return err
	}
	_, err = c.Execute(ctx, patchCertRequest)
	if err != nil {
		diag.AddError("unable to execute create certificate request", err.Error())
	}
	return err
}

func readGraphExternalCertificateAuthorityCertificate(incomingContext context.Context, diag *diag.Diagnostics, c *msgraph.Client, certificateId string) (*GraphExternalCertificateAuthorityCertificate, bool, error) {
	ctx, ctxCancel := context.WithTimeout(incomingContext, 2*time.Minute)
	defer ctxCancel()

	opts := &common.GenericOptions{
		Headers: &client.Headers{},
	}
	opts.Headers.Append("Prefer", "include-unknown-enum-members")

	getCertRequest, err := c.NewRequest(ctx, client.RequestOptions{
		ContentType:         "application/json",
		ExpectedStatusCodes: []int{http.StatusOK},
		HttpMethod:          http.MethodGet,
		OptionsObject:       opts,
		Path:                fmt.Sprintf("networkAccess/tls/externalCertificateAuthorityCertificates/%s", certificateId),
	})
	if err != nil {
		diag.AddError("unable to build create certificate request", err.Error())
		return nil, false, err
	}
	response, err := c.Execute(ctx, getCertRequest)
	if err != nil {
		if response != nil && response.StatusCode == http.StatusNotFound {
			return nil, true, nil
		}
		diag.AddError("unable to execute get certificate request", err.Error())
		return nil, response != nil && response.StatusCode == http.StatusNotFound, err
	}
	var getCertResponse GraphExternalCertificateAuthorityCertificate
	err = response.Unmarshal(&getCertResponse)
	if err != nil {
		diag.AddError("unable to unmarshal get certificate response", err.Error())
		return nil, false, err
	}
	return &getCertResponse, false, nil
}

func deleteGraphExternalCertificateAuthorityCertificate(incomingContext context.Context, diag *diag.Diagnostics, c *msgraph.Client, certificateId string) error {
	ctx, ctxCancel := context.WithTimeout(incomingContext, 10*time.Minute)
	defer ctxCancel()

	status, _, err := readGraphExternalCertificateAuthorityCertificate(incomingContext, diag, c, certificateId)
	if err != nil {
		return err
	}
	if status.Status != nil && *status.Status != "disabled" {
		payload := GraphExternalCertificateAuthorityCertificate{
			Status: pointer.To("disabled"),
		}
		err = patchGraphExternalCertificateAuthorityCertificate(incomingContext, diag, c, certificateId, payload)
		if err != nil {
			diag.AddError("unable to patch certificate resource with disabled status", err.Error())
			return err
		}
	}

	for {
		select {
		case <-ctx.Done():
			diag.AddError("timeout waiting for certificate to change to disabled for deletion", err.Error())
			return errors.New("timeout waiting for certificate to change to disabled for deletion")
		case <-time.After(10 * time.Second):
			status, _, err = readGraphExternalCertificateAuthorityCertificate(incomingContext, diag, c, certificateId)
			if err != nil {
				return err
			}
			if status.Status != nil && *status.Status == "disabled" {
				break
			}
		}
		if status.Status != nil && *status.Status == "disabled" {
			break
		}
	}

	deleteCertRequest, err := c.NewRequest(ctx, client.RequestOptions{
		ContentType:         "application/json",
		ExpectedStatusCodes: []int{http.StatusOK, http.StatusNoContent},
		HttpMethod:          http.MethodDelete,
		Path:                fmt.Sprintf("networkAccess/tls/externalCertificateAuthorityCertificates/%s", certificateId),
	})
	if err != nil {
		diag.AddError("unable to build create certificate request", err.Error())
		return err
	}
	_, err = c.Execute(ctx, deleteCertRequest)
	if err != nil {
		diag.AddError("unable to execute get certificate request", err.Error())
		return err
	}

	var notFound bool

	for {
		select {
		case <-ctx.Done():
			diag.AddError("timeout waiting for certificate to change to disabled for deletion", err.Error())
			return errors.New("timeout waiting for certificate to change to disabled for deletion")
		case <-time.After(2 * time.Second):
			_, notFound, err = readGraphExternalCertificateAuthorityCertificate(incomingContext, diag, c, certificateId)
			if notFound {
				return nil
			}
			if err != nil {
				diag.AddError("unable to read certificate status", err.Error())
				return err
			}
		}
	}
}
